### ISSUE TITLE
"TypeError:" in generate_volcanoes.py 

### ISSUE THREAD

**Issue by xherax** [VlachosGroup/ORR-Optimization#4]
Hey, I am having error while generating volcanoes from `generate_volcanoes.py` with following error
```
File "C:\Users\xherax\orrSpyder\orr_optimizer\orr_mkm.py", line 1060, in rate

if rate <=0:

TypeError: '<=' not supported between instances of 'tuple' and 'int'
```
![Tuple Error](https://user-images.githubusercontent.com/15723753/65409585-7f161d00-de01-11e9-8385-8d6988b76344.png)

I double checked enviroment variables for `PYTHONPATH ` and requirements given in the code ,
Please help to resolve this.

**Comment by xherax** [comment]
I solve it. use `rate[1]` for self in the tuple `rate`

**Comment by mpnunez** [comment]
Thank you for documenting this bug and fix. I will fix this on the master branch when I get the chance.
